// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Safely get environment variables
const getEnvVar = (key: string): string => {
  const value = import.meta.env[key];
  return typeof value === 'string' ? value : '';
};

// Get environment variables
const supabaseUrl = getEnvVar('VITE_SUPABASE_URL');
const supabaseAnonKey = getEnvVar('VITE_SUPABASE_ANON_KEY');

// Validate URL format
const isValidUrl = (url: string): boolean => {
  try {
    new URL(url);
    return true;
  } catch {
    return false;
  }
};

// Create a default export for the supabase client
let supabaseClient: any = null;

// Check for placeholder values
const isPlaceholderUrl = supabaseUrl.includes('your_supabase') || supabaseUrl === '';
const isPlaceholderKey = supabaseAnonKey.includes('your_supabase') || supabaseAnonKey === '';

if (isPlaceholderUrl || isPlaceholderKey) {
  console.error(
    'Supabase credentials not configured. Please set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in your .env file'
  );
} else if (!isValidUrl(supabaseUrl)) {
  console.error('Invalid VITE_SUPABASE_URL format:', supabaseUrl);
} else {
  try {
    // Create the Supabase client
    supabaseClient = createClient<Database>(supabaseUrl, supabaseAnonKey, {
      auth: {
        persistSession: true,
        autoRefreshToken: true,
        storage: localStorage,
        flowType: 'pkce',
        detectSessionInUrl: true
      }
    });
    console.log('Supabase client initialized successfully');
  } catch (error) {
    console.error('Error initializing Supabase client:', error);
  }
}

// Export the client
export const supabase = supabaseClient;
