// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Safely get environment variables
const getEnvVar = (key: string): string => {
  const value = import.meta.env[key];
  return typeof value === 'string' ? value : '';
};

// Get environment variables
const supabaseUrl = getEnvVar('VITE_SUPABASE_URL');
const supabaseAnonKey = getEnvVar('VITE_SUPABASE_ANON_KEY');

// Create a default export for the supabase client
let supabaseClient: any = null;

try {
  if (!supabaseUrl) {
    console.error('Missing VITE_SUPABASE_URL environment variable');
  } else if (!supabaseAnonKey) {
    console.error('Missing VITE_SUPABASE_ANON_KEY environment variable');
  } else {
    // Create the Supabase client
    supabaseClient = createClient<Database>(supabaseUrl, supabaseAnonKey, {
      auth: {
        persistSession: true,
        autoRefreshToken: true,
        storage: localStorage,
        flowType: 'pkce',
        detectSessionInUrl: true
      }
    });
    console.log('Supabase client initialized successfully');
  }
} catch (error) {
  console.error('Error initializing Supabase client:', error);
}

// Export the client
export const supabase = supabaseClient;
